blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name
from django.views.decorators.cache import never_cache, cache_page

urlpatterns = [
    path("create", BlogCreateView.as_view(), name="create"),
    path("", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="view"),
    path("edit/<int:pk>/", BlogUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from config import settings
from message.apps import MessageConfig

app_name = MessageConfig.name

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("client.urls", namespace="client")),
    path("message/", include("message.urls", namespace="message")),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.models import Attempt
from mailing.views import (
    SettingsListView,
    SettingsDetailView,
    SettingsUpdateView,
    SettingsDeleteView,
    SettingsCreateView,
    AttemptListView,
)
from django.views.decorators.cache import never_cache, cache_page

app_name = MailingConfig.name

urlpatterns = [
    path("", cache_page(60)(SettingsListView.as_view()), name="settings_list"),
    path("<int:pk>/", SettingsDetailView.as_view(), name="settings_detail"),
    path(
        "update/<int:pk>/",
        never_cache(SettingsUpdateView.as_view()),
        name="settings_update",
    ),
    path("delete/<int:pk>/", SettingsDeleteView.as_view(), name="settings_delete"),
    path("create/", never_cache(SettingsCreateView.as_view()), name="settings_create"),
    path("attempt_list/", AttemptListView.as_view(), name="attempt_list"),
]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Settings(models.Model):
    frequency_tuple = (
        ("daily", "раз в день"),
        ("weekly", "раз в неделю"),
        ("monthly", "раз в месяц"),
    )
    status_tuple = (
        ("завершена", "завершена"),
        ("создана", "создана"),
        ("запущена", "запущена"),
    )
    first_mailing_date = models.DateTimeField(verbose_name="дата первой отправки")
    frequency = models.CharField(
        max_length=150, verbose_name="периодичность", choices=frequency_tuple
    )
    status = models.CharField(
        max_length=150, verbose_name="статус отправки", choices=status_tuple
    )

    message = models.OneToOneField(
        "message.Message",
        on_delete=models.CASCADE,
        verbose_name="сообщение",
        **NULLABLE,
    )
    client = models.ManyToManyField("client.Client", verbose_name="клиент", **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name="активна")

    owner = models.ForeignKey(
        User,
        verbose_name="владелец",
        help_text="Укажите владельца рассылки",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return f"{self.first_mailing_date}"

    class Meta:
        verbose_name = "настройки"
        verbose_name_plural = "настройки"
        permissions = [
            ("can_disabled_mailing", "can_disabled_mailing"),
        ]


class Attempt(models.Model):
    status_tuple = (
        ("успешно", "успешно"),
        ("не успешно", "не успешно"),
    )
    last_attempt_date = models.DateTimeField(
        auto_now_add=True, verbose_name="дата последней попытки"
    )
    status = models.CharField(
        max_length=150, verbose_name="статус попытки", choices=status_tuple, **NULLABLE
    )
    server_response = models.CharField(
        max_length=150, verbose_name="ответ почтового сервера", **NULLABLE
    )

    mailing = models.ForeignKey(
        Settings, on_delete=models.CASCADE, verbose_name="рассылка"
    )

    def __str__(self):
        return f"{self.last_attempt_date}"

    class Meta:
        verbose_name = "попытка"
        verbose_name_plural = "попытки"

mailing/forms.py
from django import forms

from client.models import Client
from message.models import Message
from .mixins import StyledFormMixin
from .models import Settings


class SettingsForm(forms.ModelForm):
    class Meta:
        model = Settings
        user = forms.ChoiceField(required=True)
        fields = [
            "first_mailing_date",
            "frequency",
            "status",
            "message",
            "client",
            "is_active",
        ]


class MailingModeratorForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = Settings
        fields = ["is_active"]


class MailingModeratorFormOwner(StyledFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)  # Извлекаем пользователя из аргументов
        super(MailingModeratorFormOwner, self).__init__(*args, **kwargs)

        if user:
            # Фильтруем клиентов по текущему пользователю
            self.fields["client"].queryset = Client.objects.filter(owner=user)

        if user:
            # Фильтруем сообщения по текущему пользователю
            self.fields["message"].queryset = Message.objects.filter(owner=user)

    class Meta:
        model = Settings
        # user = forms.ChoiceField(required=True)
        fields = [
            "first_mailing_date",
            "frequency",
            "status",
            "message",
            "client",
            "is_active",
        ]
        widgets = {
            "client": forms.CheckboxSelectMultiple(),  # Для удобного выбора клиентов
        }

mailing/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    CreateView,
)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from mailing.cron import send_mailing_email
from mailing.forms import SettingsForm, MailingModeratorForm, MailingModeratorFormOwner
from mailing.models import Settings, Attempt


class SettingsListView(LoginRequiredMixin, ListView):
    model = Settings
    paginate_by = 3
    extra_context = {"title": "Рассылки"}

    def get_queryset(self):
        queryset = super().get_queryset()
        sort_by = self.request.GET.get(
            "sort", "client"
        )  # По умолчанию сортировка по имени
        return queryset.order_by(sort_by)


class SettingsDetailView(LoginRequiredMixin, DetailView):
    model = Settings
    permission_required = "mailing.settings_list"
    extra_context = {"title": "Рассылка"}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"] = self.object  # объект Settings
        return context


class SettingsCreateView(LoginRequiredMixin, CreateView):
    model = Settings
    form_class = MailingModeratorFormOwner
    extra_context = {"title": "Форма по добавлению"}

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()  # Получаю стандартные аргументы формы
        kwargs["user"] = self.request.user  # Передаю текущего пользователя в форму
        return kwargs

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Устанавливаю владельца

        mailing_item = form.save()  # Сначала сохраняю объект Settings

        # После этого отправляю письма
        selected_clients = form.cleaned_data["client"]  # Получаю выбранных клиентов
        send_mailing_email(
            mailing_item, selected_clients
        )  # Отправляю сообщения только выбранным клиентам

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("mailing:settings_list")


class SettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = Settings

    form_class = MailingModeratorFormOwner
    extra_context = {"title": "Форма по редактированию"}

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.owner = self.request.user

        mailing_item = form.save()

        selected_clients = form.cleaned_data["client"]
        send_mailing_email(mailing_item, selected_clients)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("mailing:settings_list")


class SettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = Settings

    extra_context = {"title": "Удаление рассылки"}

    success_url = reverse_lazy("mailing:settings_list")


class AttemptListView(LoginRequiredMixin, ListView):
    model = Attempt
    template_name = "mailing/attempt_list.html"
    context_object_name = "attempts"

    def get_queryset(self):
        return Attempt.objects.all().order_by("-last_attempt_date")

mailing/templates/mailing/attempt_list.html
{% extends 'client/base.html' %}

{% block content %}
<div class="container">
    <h1>Отчет о попытках рассылок</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Дата последней попытки</th>
                <th>Статус</th>
                <th>Ответ почтового сервера</th>
                <th>Рассылка</th>
            </tr>
        </thead>
        <tbody>
            {% for attempt in attempts %}
                <tr>
                    <td>{{ attempt.last_attempt_date }}</td>
                    <td>{{ attempt.get_status_display }}</td> <!-- Отображаем человекочитаемое значение статуса -->
                    <td>{{ attempt.server_response }}</td>
                    <td>{{ attempt.mailing }}</td> <!-- Отображаем связанную рассылку -->
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">Нет доступных попыток рассылок.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mailing/templates/mailing/settings_confirm_delete.html
{% extends 'client/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Вы действительно хотите удалить рассылку сообщения "{{object.message}}"? </p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailing:settings_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/settings_detail.html
{% extends 'client/base.html' %}
{% block content %}
<div class="col-12">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Рассылка: {{object}}</h4>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <th scope="row"> Сообщение:</th>
                    <td> {{ object.message }}</td>
                    <th scope="row"></th>
                    <td colspan="2"></td>

                </td>
                <th scope="row"></th>
                <td colspan="2"></td>
                </tr>
                <tr>
                    <th scope="row"> Статус:</th>
                    <td> {{ object.status }}</td>
                    <th scope="row"></th>
                    <td colspan="2"></td>
                </tr>
                <tr>
                    <th scope="row"> Отправка:</th>
                    <td> {{ object.frequency }}</td>
                    <th scope="row"></th>
                    <td colspan="2"></td>
                </tr>
                <tr>
                    {% for attempt_item in settings.attempt_set.all %}
                    <th scope="row"> Информация об отправки:</th>
                    <td colspan="2">Дата отправки: {{ attempt_item.last_attempt_date}}</td>
                    <td colspan="2">Ответ сервера: {{ attempt_item.server_response}}</td>
                    <th scope="row"> Статус:</th>
                    <td colspan="2">{{ attempt_item.status}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/settings_form.html
{% extends 'client/base.html' %}
{% block content %}
<div class="input-group mx-auto p-2">
    <form method="post" style="text-align:center" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}<br>
        <button class="p-2 btn btn-outline-warning" type="submit">Сохранить</button>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/settings_list.html
{% extends 'client/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">Список сообщений</div>
                <div class="card-body">
                    <a href="{% url 'mailing:settings_create' %}" class="btn btn-primary">Создать новую рассылку</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% for object in object_list %}
<div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-body">
            {% if user == object.owner or perms.mailing.can_disabled_mailing %}
            <h5 class="card-title pricing-card-title">{{ object.message }}</h5><br>

            <div class="btn-group" role="group" aria-label="Basic outlined example">

                <a href="{% url 'mailing:settings_detail' object.pk %}" type="button"
                   class="w-100 btn btn-outline-success">Открыть</a>
                <a href="{% url 'mailing:settings_update' object.pk %}" type="button"
                   class="w-100 btn btn-outline-warning">Редактировать</a>
            </div>
            {% endif %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
                {% if user == object.owner%}
                <a href="{% url 'mailing:settings_delete' object.pk %}" type="button"
                   class="w-100 btn btn-outline-danger">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    {% endblock %}