blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name
from django.views.decorators.cache import never_cache, cache_page

urlpatterns = [
    path("create", BlogCreateView.as_view(), name="create"),
    path("", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="view"),
    path("edit/<int:pk>/", BlogUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

client/urls.py
from django.urls import path

from client.apps import ClientConfig
from client.views import ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, ClientCreateView, \
    HomeView
from django.views.decorators.cache import cache_page

app_name = ClientConfig.name

urlpatterns = [
    path("", cache_page(60)(HomeView.as_view()), name="home"),
    path('client_list',ClientListView.as_view(), name='client_list'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from config import settings
from message.apps import MessageConfig

app_name = MessageConfig.name

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("client.urls", namespace="client")),
    path("message/", include("message.urls", namespace="message")),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.models import Attempt
from mailing.views import (
    SettingsListView,
    SettingsDetailView,
    SettingsUpdateView,
    SettingsDeleteView,
    SettingsCreateView,
    AttemptListView,
)
from django.views.decorators.cache import never_cache, cache_page

app_name = MailingConfig.name

urlpatterns = [
    path("", cache_page(60)(SettingsListView.as_view()), name="settings_list"),
    path("<int:pk>/", SettingsDetailView.as_view(), name="settings_detail"),
    path(
        "update/<int:pk>/",
        never_cache(SettingsUpdateView.as_view()),
        name="settings_update",
    ),
    path("delete/<int:pk>/", SettingsDeleteView.as_view(), name="settings_delete"),
    path("create/", never_cache(SettingsCreateView.as_view()), name="settings_create"),
    path("attempt_list/", AttemptListView.as_view(), name="attempt_list"),
]

message/urls.py
from django.urls import path

from message.apps import MessageConfig
from message.views import (
    MessageListView,
    MessageDetailView,
    MessageUpdateView,
    MessageDeleteView,
    MessageCreateView,
)
from django.views.decorators.cache import never_cache

app_name = MessageConfig.name

urlpatterns = [
    path("", MessageListView.as_view(), name="message_list"),
    path("<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path(
        "update/<int:pk>/",
        never_cache(MessageUpdateView.as_view()),
        name="message_update",
    ),
    path("delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"),
    path("create/", never_cache(MessageCreateView.as_view()), name="message_create"),
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView

from users.views import RegisterView, ProfileView, email_verification, PasswordResetView

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
]

client/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Client(models.Model):
    first_name = models.CharField(max_length=150, verbose_name="имя")
    last_name = models.CharField(max_length=150, verbose_name="фамилия")
    email = models.EmailField(verbose_name="почта", unique=True)
    comment = models.TextField(verbose_name="комментарий")

    owner = models.ForeignKey(
        User,
        verbose_name="владелец",
        help_text="Укажите владельца рассылки",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return f"{self.email} ({self.first_name} {self.last_name})"

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"

client/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    CreateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from client.models import Client


class HomeView(ListView):
    model = Client
    template_name = "client/home.html"


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    paginate_by = 3
    extra_context = {"title": "Клиенты"}

    def get_object(self, queryset=None):
        return Client.objects.filter(
            owner=self.request.user
        ).first()  # Возвращаем сообщение текущего пользователя, если он есть, иначе None

    def get_queryset(self):
        queryset = super().get_queryset()
        sort_by = self.request.GET.get(
            "sort", "email"
        )  # По умолчанию сортировка по email
        return queryset.order_by(sort_by)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    extra_context = {"title": "Клиент"}
    permission_required = "mailing.settings_list"


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ("first_name", "last_name", "email", "comment")

    extra_context = {"title": "Форма по добавлению"}

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Устанавливаем владельца
        return super().form_valid(form)

    # permission_required = "mailing.settings_list"

    def get_success_url(self):
        return reverse("client:client_list")


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client

    fields = ("first_name", "last_name", "email", "comment", "owner")
    extra_context = {"title": "Форма по редактированию"}

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Устанавливаем владельца
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("client:client_detail", args=[self.kwargs.get("pk")])


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client

    extra_context = {"title": "Удаление клиента"}
    success_url = reverse_lazy("client:client_list")

client/templates/client/includes/menu.html
<h3>Сизый голубь - это лучший сервис по рассылке писем Вашим клиентам!</h3>

<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">


    <!-- Кнопка выпадающего списка вправо по умолчанию -->
    <div class="btn-group dropend">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Меню: клиенты, сообщения, рассылки, статьи
        </button>
        <ul class="dropdown-menu">
            <!-- Ссылки выпадающего меню -->
            <a class="dropdown-item" href="{% url 'client:client_list' %}">Мои клиенты</a>
            <a class="dropdown-item" href="{% url 'message:message_list' %}">Мои сообщения</a>
            <a class="dropdown-item" href="{% url 'mailing:settings_list' %}">Мои рассылки</a>
            <a class="dropdown-item" href="{% url 'mailing:attempt_list' %}">Отчетность по рассылкам</a>
            <a class="dropdown-item" href="{% url 'blog:blog_list' %}">Интересные статьи</a>

        </ul>
    </div>



    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary mx-2" href="{% url 'client:home' %}">Статистика рассылок</a>
        <a class="p-2 btn btn-outline-primary mx-2" href="{% url 'users:profile' %}">Профиль</a>
        <a class="p-2 btn btn-outline-primary mx-2" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary mx-2" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary mx-2" href="{% url 'users:password_reset' %}">Восстановить пароль</a>
        <a class="p-2 btn btn-outline-primary mx-2" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

client/templates/client/includes/page_name.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title> {{title}} </title>