blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name
from django.views.decorators.cache import never_cache, cache_page

urlpatterns = [
    path("create", BlogCreateView.as_view(), name="create"),
    path("", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="view"),
    path("edit/<int:pk>/", BlogUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from config import settings
from message.apps import MessageConfig

app_name = MessageConfig.name

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("client.urls", namespace="client")),
    path("message/", include("message.urls", namespace="message")),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify

from mailing.models import NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, default=" ", unique=True)
    content = models.TextField(default=" ")
    preview_image = models.ImageField(upload_to="blog_previews/", **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    views_count = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

blog/views.py
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DetailView,
    DeleteView,
)
from django.urls import reverse_lazy
from blog.models import Blog

from django.urls import reverse
from pytils.translit import slugify

from django.contrib.auth.mixins import LoginRequiredMixin


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = (
        "title",
        "content",
        "preview_image",
        "is_published",
        "views_count",
    )
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = (
        "title",
        "content",
        "preview_image",
        "is_published",
        "views_count",
    )

    # success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:view", args=[self.kwargs.get("pk")])


class BlogListView(ListView):
    model = Blog
    template_name = "blog/blog_list.html"
    paginate_by = 3

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/blog_confirm_delete.html
{% extends 'client/base.html' %}

{% block content %}
  <h1>Удалить пост</h1>

  <form method="post">
    {% csrf_token %}
      <p>Хотите удалить этот материал "{{object.title}}"?</p>
    <button type="submit" class="btn btn-danger">Подтвердить</button>
      <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отмена</a>
  </form>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "client/base.html" %}

{% block content %}
<div style="max-width: 1100px; margin: 0 auto;">
    <h1 style="text-align: left;">Статья:"{{ object.title }}" ({{object.slug}})</h1>
    {% if blog.preview_image %}
    <img src="{{ blog.preview_image.url }}" alt="Preview Image"
         style="display: block; margin: 0 auto; max-width: 100%;">
    {% else %}
    <p style="text-align: left;">Изображение для предварительного просмотра недоступно.</p>
    {% endif %}
    <p>{{ blog.content }}</p>
    <p style="text-align: left;">Просмотры: {{ blog.views_count }}</p>
    <div style="text-align: left;">
        {% if user.is_authenticated and perms.blog.add_blog %}
        <a href="{% url 'blog:edit' blog.pk %}" style="margin-right: 10px;">Изменить</a>
        <a href="{% url 'blog:delete' blog.pk %}" style="margin-right: 10px;">Удалить</a>
        <a href="{% url 'blog:blog_list' %}">Вернуться к списку</a>
        {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "client/base.html" %}

{% block content %}
<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Добавить новую статью</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                        {% csrf_token %}
                        {{form.as_p}}


                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-success">
                        {% if object %}
                        Изменить
                        {% else %}
                        Создать
                        {% endif %}


                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'client/base.html' %}
{% load my_tags %}
{% load static %}

{% block content %}
<div class="container mb-2 mt-2">
    {% if user.is_authenticated and perms.blog.add_blog %}
    <a class="btn btn-primary" href="{% url 'blog:create' %}" role="button">Добавить статью</a>
    {% endif %}
</div>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
    <div class="col">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">
                    {{ object | title }}
                </p>
                {% if object.preview_image %}
                <img src="{{ object.preview_image.url }}" class="img-fluid img-thumbnail" alt="{{ object.title }}">
                {% endif %}

                <div class="d-grid gap-2 d-md-block">
                    <div class="btn-group">
                        <a class="btn btn-success" href="{% url 'blog:view' object.pk %}" role="button">Посмотреть</a>

                        {% if perms.blog.add_blog %}
                        <a class="btn btn-warning" href="{% url 'blog:edit' object.pk %}" role="button">Изменить</a>
                        <a class="btn btn-danger" href="{% url 'blog:delete' object.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}