blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name
from django.views.decorators.cache import never_cache, cache_page

urlpatterns = [
    path("create", BlogCreateView.as_view(), name="create"),
    path("", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="view"),
    path("edit/<int:pk>/", BlogUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

client/urls.py
from django.urls import path

from client.apps import ClientConfig
from client.views import ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, ClientCreateView, \
    HomeView
from django.views.decorators.cache import cache_page

app_name = ClientConfig.name

urlpatterns = [
    path("", cache_page(60)(HomeView.as_view()), name="home"),
    path('client_list',ClientListView.as_view(), name='client_list'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from config import settings
from message.apps import MessageConfig

app_name = MessageConfig.name

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("client.urls", namespace="client")),
    path("message/", include("message.urls", namespace="message")),
    path("mailing/", include("mailing.urls", namespace="mailing")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.urls import path

from message.apps import MessageConfig
from message.views import (
    MessageListView,
    MessageDetailView,
    MessageUpdateView,
    MessageDeleteView,
    MessageCreateView,
)
from django.views.decorators.cache import never_cache

app_name = MessageConfig.name

urlpatterns = [
    path("", MessageListView.as_view(), name="message_list"),
    path("<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path(
        "update/<int:pk>/",
        never_cache(MessageUpdateView.as_view()),
        name="message_update",
    ),
    path("delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"),
    path("create/", never_cache(MessageCreateView.as_view()), name="message_create"),
]

message/models.py
from django.db import models

from users.models import User


class Message(models.Model):
    subject = models.CharField(max_length=150, verbose_name="тема письма")
    text = models.TextField(verbose_name="текст сообщения")
    owner = models.ForeignKey(
        User,
        verbose_name="владелец",
        help_text="Укажите владельца сообщения",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    class Meta:
        verbose_name = "сообщение"
        verbose_name_plural = "сообщения"
        permissions = [
            ("can_view_subject_message", "can_view_subject_message"),
            ("can_view_text_message", "can_view_text_message"),
        ]

    def __str__(self):
        return f"{self.subject}"

message/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    CreateView,
)

from message.models import Message

from django.contrib.auth.mixins import LoginRequiredMixin


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    paginate_by = 3
    extra_context = {"title": "Сообщения"}

    def get_queryset(self):
        queryset = super().get_queryset()
        sort_by = self.request.GET.get(
            "sort", "subject"
        )  # По умолчанию сортировка по имени
        return queryset.order_by(sort_by)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    extra_context = {"title": "Сообщение"}


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = (
        "subject",
        "text",
    )

    extra_context = {"title": "Форма по добавлению"}

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Устанавливаем владельца
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            "mailing:settings_list"
        )  # Укажите URL для перенаправления после успешного создания


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    fields = (
        "subject",
        "text",
    )
    extra_context = {"title": "Форма по редактированию"}

    def get_success_url(self):
        return reverse("message:message_detail", args=[self.kwargs.get("pk")])


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message

    extra_context = {"title": "Удаление сообщения"}
    success_url = reverse_lazy("message:message_list")

message/templates/message/message_confirm_delete.html
{% extends 'client/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Вы действительно хотите удалить сообщение: "{{object.subject}}"? </p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'client:client_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

message/templates/message/message_detail.html
{% extends 'client/base.html' %}
{% block content %}
<div class="col-6">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">{{object.subject}}</h4>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <th scope="row"> Текс сообщения: </th>
                    <td> {{ object.text }} </td>
                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}

message/templates/message/message_form.html
{% extends 'client/base.html' %}
{% block content %}
<div class="input-group mx-auto p-2">
    <form method="post" style="text-align:center" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}<br>
        <button class="p-2 btn btn-outline-warning" type="submit">Сохранить</button>
    </form>
</div>
{% endblock %}

message/templates/message/message_list.html
{% extends 'client/base.html' %}
{% block content %}


<div class="col">
    <div class="card">
        <div class="card-body">
            <a href="{% url 'message:message_create' %}" class="btn btn-primary">Создать новое сообщение</a>
        </div>
    </div>
</div>


<div class="col">
    <div class="card-header">Список сообщений</div>
</div>
{% for object in object_list %}

<div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
            {% if user == object.owner or perms.mailing.can_view_mailing %}
            <h4 class="my-0 fw-normal">{{object.subject}}</h4>
            {% endif %}
        </div>
        <div class="card-body">
            <div class="btn-group" role="group" aria-label="Basic outlined example">
                {% if user == object.owner %}
                <a href="{% url 'message:message_detail' object.pk %}" type="button"
                   class="w-100 btn btn-outline-success">Открыть</a>
                <a href="{% url 'message:message_update' object.pk %}" type="button"
                   class="w-100 btn btn-outline-warning">Редактировать</a>
                <a href="{% url 'message:message_delete' object.pk %}" type="button"
                   class="w-100 btn btn-outline-danger">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}